---
ID: "a6539687-7e97-4c8c-82c2-837db6c0b641"
Parent: "ea28baf4-62fa-4fa9-80f9-07c39608e5e7"
Template: "99f8905d-4a87-4eb8-9f8b-a9bebfb3add6"
Path: /sitecore/layout/Renderings/Commerce/Catalog/Product Details
DB: master
SharedFields:
- ID: "51b435bc-f7b9-478a-9c51-52916af96ff5"
  Hint: Path
  Value: ~/Views/ProductDetails.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161014T094306Z
