---
ID: "5e9cf1ea-6578-b33c-5948-fabe155d0e9c"
Parent: "192acfae-580b-2bd2-2cda-e874317bf9c6"
Template: "192acfae-580b-2bd2-2cda-e874317bf9c6"
Path: /sitecore/templates/User Defined/uCommerce definitions/Software Variant/__Standard Values
DB: master
SharedFields:
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: "{D09D126F-A9A0-4744-BE3C-A97143D8CFEF}"
Languages:
- Language: en
  Versions:
  - Version: 1
