---
ID: "8e69d8f9-cde7-2ad4-38df-c1b132f4a702"
Parent: "86fa3a87-b0a3-4a4b-bbe1-e75398d267d5"
Template: "86fa3a87-b0a3-4a4b-bbe1-e75398d267d5"
Path: /sitecore/templates/User Defined/uCommerce definitions/ProductBaseTemplate/__Standard Values
DB: master
SharedFields:
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: "{D09D126F-A9A0-4744-BE3C-A97143D8CFEF}"
Languages:
- Language: en
  Versions:
  - Version: 1
