---
ID: "c6853b1b-f1c7-fc43-3540-d08979661b1f"
Parent: "a6b2d664-279f-479d-24f0-df180a6e7a37"
Template: "a6b2d664-279f-479d-24f0-df180a6e7a37"
Path: /sitecore/templates/User Defined/uCommerce definitions/Shoe Variant/__Standard Values
DB: master
SharedFields:
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: "{D09D126F-A9A0-4744-BE3C-A97143D8CFEF}"
Languages:
- Language: en
  Versions:
  - Version: 1
