---
ID: "96fc75f0-f386-4d6d-b739-3a7c72487cac"
Parent: "7919567a-faa2-4504-9c31-63a2cf67b551"
Template: "86fa3a87-b0a3-4a4b-bbe1-e75398d267d5"
Path: /sitecore/content/AvenueClothing/Product Details
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161018T101135Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
