---
ID: "1b707c14-d1b1-1c78-e04c-da14911877ee"
Parent: "d06f2323-1cbf-927d-28fa-42f074028b38"
Template: "d06f2323-1cbf-927d-28fa-42f074028b38"
Path: /sitecore/templates/User Defined/uCommerce definitions/Shirt Variant/__Standard Values
DB: master
SharedFields:
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: "{D09D126F-A9A0-4744-BE3C-A97143D8CFEF}"
Languages:
- Language: en
  Versions:
  - Version: 1
