---
ID: "abd9f13f-dfac-4ed9-8c23-e0a9c5bb19c9"
Parent: "a3585578-10f9-48f3-afe4-b568ab275a6f"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/User Defined/uCommerce definitions/ProductCategoryTemplate
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /sitecore%20modules/Shell/ucommerce/images/ui/map.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: "{1930BBEB-7805-471A-A3BE-4858AC7CF696}"
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: "{D09D126F-A9A0-4744-BE3C-A97143D8CFEF}"
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{ADA260E5-C2CA-B8BB-3CE8-03B6C8A9CE7C}"
Languages:
- Language: en
  Versions:
  - Version: 1
