---
ID: "9336b4dd-e895-4a97-a252-5ebf3776b8a1"
Parent: "b349d3bd-8626-4e03-9850-4dae6533e6fa"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Common/Avenue Clothing/AvenueClothing/Highlighted Products/Products
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: DataSource=/sitecore/uCommerce/Products&ExcludeTemplatesForSelection=Bucket,Template Folder
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Treelist
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161012T080410Z
